CREATE TABLE burgers (
id INT AUTO_INCREMENT NOT NULL
, burger_name VARCHAR(50) NOT NULL
, devoured BOOLEAN DEFAULT false
, createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
, PRIMARY KEY (id)
);

SELECT * FROM burgers;